# Generated by Django 4.1.3 on 2022-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField(error_messages='Vui lòng nhập lại', help_text='Big integer field', verbose_name='Big Integer Field')),
                ('boolean_field', models.BooleanField(error_messages='Vui lòng nhập lại', help_text='Binary Field', verbose_name='Binary Field')),
                ('select_muitiple_filed', models.CharField(help_text='Select Field', max_length=100, verbose_name='Select Field')),
                ('binary_field', models.BinaryField(error_messages='Vui lòng nhập lại', help_text='Binary Field', verbose_name='Binary Field')),
                ('char_filed', models.CharField(error_messages='Vui lòng nhập lại', help_text='Char Field', max_length=100, null=True, verbose_name='Char Field')),
                ('select_filed', models.CharField(choices=[('1', 'Hello'), ('2', 'World')], help_text='Select Field', max_length=100, verbose_name='Select Field')),
                ('date_filed', models.DateField(error_messages='Vui lòng nhập lại', help_text='Date Field', verbose_name='Date Field')),
                ('dateTime_filed', models.DateTimeField(error_messages='Vui lòng nhập lại', help_text='DateTime Field', verbose_name='DateTime Field')),
                ('duration_filed', models.DurationField(error_messages='Vui lòng nhập lại', help_text='Duration Field', verbose_name='Duration Field')),
                ('email_filed', models.EmailField(error_messages='Vui lòng nhập lại', help_text='Email Field', max_length=254, verbose_name='Email Field')),
                ('float_filed', models.FloatField(error_messages='Vui lòng nhập lại', help_text='Float Field', verbose_name='Float Field')),
                ('integer_filed', models.IntegerField(error_messages='Vui lòng nhập lại', help_text='Integer Field', verbose_name='Integer Field')),
                ('decimal_filed', models.DecimalField(decimal_places=3, error_messages='Vui lòng nhập lại', help_text='Decimal Field', max_digits=12, verbose_name='Decimal Field')),
                ('image_filed', models.ImageField(error_messages='Vui lòng nhập lại', help_text='Image Field', upload_to='', verbose_name='Image Field')),
                ('json_field', models.JSONField(error_messages='Vui lòng nhập lại', help_text='JSON Field', verbose_name='JSON Field')),
                ('file_filed', models.FileField(default='', error_messages='Vui lòng nhập lại', help_text='File Field', upload_to='', verbose_name='File Field')),
                ('generic_ip_address_filed', models.GenericIPAddressField(error_messages='Vui lòng nhập lại', help_text='Generic IP Address Field', verbose_name='Generic IP Address Field')),
                ('positive_integer_field', models.PositiveIntegerField(error_messages='Vui lòng nhập lại', help_text='Positive Integer Field', verbose_name='Positive Integer Field')),
                ('positive_small_integer_field', models.PositiveSmallIntegerField(error_messages='Vui lòng nhập lại', help_text='Positive Field', verbose_name='Positive Field')),
                ('slug_filed', models.SlugField(error_messages='Vui lòng nhập lại', help_text='Slug Field', verbose_name='Slug Field')),
                ('small_integer_field', models.SmallIntegerField(error_messages='Vui lòng nhập lại', help_text='Small Field', verbose_name='Small Field')),
                ('time_filed', models.TimeField(error_messages='Vui lòng nhập lại', help_text='Time Field', verbose_name='Time Field')),
                ('text_field', models.TextField(error_messages='Vui lòng nhập lại', help_text='Text File', verbose_name='Text File')),
                ('url_filed', models.URLField(error_messages='Vui lòng nhập lại', help_text='Url File', verbose_name='Url File')),
                ('uuid_filed', models.UUIDField(error_messages='Vui lòng nhập lại', help_text='UUID Field', verbose_name='UUID Field')),
            ],
        ),
    ]
