# Generated by Django 4.1.3 on 2022-11-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfield', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='boolean_field',
            field=models.BooleanField(error_messages='Vui lòng nhập lại', help_text='Boolean Field', verbose_name='Boolean Field'),
        ),
    ]
